version: "3.7"
services:
  api_service:
    build: .
    restart: always
    ports:
      - 8081:8081
    networks:
      - springapimysql-net
    environment:
      - spring.datasource.url=jdbc:mysql://localhost/library   
    depends_on:
      - mysqldb
    
    volumes:
      - .m2:/root/.m2
      
  mysqldb:
    image: "mysql:8.0"
    restart: always
    ports:
      - 3306:3306
    networks:
      - springapimysql-net  
    environment:
      MYSQL_DATABASE: library
      MYSQL_USER: mthobisikhumalo
      MYSQL_PASSWORD: LeTrinity5470083_
      MYSQL_ROOT_PASSWORD: 
networks:
  springapimysql-net: